title: Alien language
hero_image: images/banner.png
description: Create your own alien language to move a sprite
theme: orange
listed: false
copyedit: false
technologies: scratch
software: scratch
version: 4.0.0
last_tested: "2019-06-04"
steps:
  - title: Introduction
  - title: Using a pretrained model
  - title: Create new project
  - title: Create alien words
  - title: Train new machine learning model
  - title: Use Alien words in Scratch
  - title: "Challenge: add new commands"
    challenge: true
  - title: What next?