title: Alien language
hero_image: images/banner.png
description: Create your own alien language to move a sprite
theme: orange
listed: true
copyedit: true
technologies: scratch
software: scratch
version: 4.0.0
last_tested: "2019-06-04"
steps:
  - title: Introduction
  - title: Use a pretrained model
  - title: Create a new project
  - title: Create alien words
  - title: Train a new machine learning model
  - title: Use alien words in Scratch
  - title: "Challenge: add new commands"
    challenge: true
  - title: What next?
