---
title: エイリアン語
hero_image: images/banner.png
description: 自分だけのエイリアン語でスプライトを動かそう
theme: orange
listed: true
copyedit: true
technologies: scratch
software: scratch
version: 4.0.0
last_tested: "2019-06-04"
steps:
  - 
    title: はじめに
  - 
    title: 事前学習ずみのモデルを使用する
  - 
    title: Create a new project
  - 
    title: Create alien words
  - 
    title: Train a new machine learning model
  - 
    title: Use alien words in Scratch
  - 
    title: "Challenge: add new commands"
    challenge: true
  - 
    title: What next?
