---
title: Alien-Sprache
hero_image: images/banner.png
description: Erstelle deine eigene Alien-Sprache, um eine Figur zu bewegen
theme: orange
listed: true
copyedit: true
technologies: Scratch
software: Scratch
version: 4.0.0
last_tested: '2019-06-04'
steps:
  - 
    title: Was du machen wirst
  - 
    title: Set up the project
  - 
    title: Invent two words
    completion:
      - engaged
  - 
    title: Train the model
  - 
    title: Control the alien
    completion:
      - internal
      - external
  - 
    title: 'Challenge'
    challenge: true
  - 
    title: What can you do now?
    completion:
