---
title: Alien-Sprache
hero_image: images/banner.png
description: Erstelle deine eigene Alien-Sprache, um eine Figur zu bewegen
theme: orange
listed: true
copyedit: true
technologies: Scratch
software: Scratch
version: 4.0.0
last_tested: '2019-06-04'
steps:
- title: Einleitung
- title: Verwende ein vortrainiertes Modell
- title: Erstelle ein neues Projekt
  completion:
  - engaged
- title: Erstelle außerirdische Wörter
- title: Trainiere ein neues maschinelles Lernmodell
- title: Verwende außerirdische Wörter in Scratch
  completion:
  - internal
- title: 'Herausforderung: Neue Befehle hinzufügen'
  challenge: true
