---
title: Linguagem alienígena
hero_image: images/banner.png
description: Crie sua própria linguagem alienígena para mover um ator
theme: laranja
listed: true
copyedit: true
technologies: scratch
software: scratch
version: 3
last_tested: '2019-06-04'
steps:
  - 
    title: O que você vai fazer
  - 
    title: Set up the project
  - 
    title: Invent two words
    completion:
      - engaged
  - 
    title: Train the model
  - 
    title: Control the alien
    completion:
      - internal
      - external
  - 
    title: 'Challenge'
    challenge: true
  - 
    title: What can you do now?
    completion:
