---
title: Linguagem alienígena
hero_image: images/banner.png
description: Crie sua própria linguagem alienígena para mover um ator
theme: orange
listed: true
copyedit: true
technologies: scratch
software: scratch
version: 4.0.0
last_tested: '2019-06-04'
steps:
- title: Introdução
- title: Use um modelo pré-treinado
- title: Crie um novo projeto
  completion:
  - engaged
- title: Crie palavras alienígenas
- title: Treine um novo modelo de aprendizado de máquina
- title: Use palavras alienígenas no Scratch
  completion:
  - internal
- title: 'Desafio: adicionar novos comandos'
  challenge: true
