---
title: لغة غريبة
hero_image: images/banner.png
description: قم بإنشاء لغة كائن الفضاء الخاصة بك لتحريك الكائن
theme: البرتقالي
listed: true
copyedit: true
technologies: scratch
software: scratch
version: 4.0.0
last_tested: '2019-06-04'
steps:
  - 
    title: What you will make
  - 
    title: Set up the project
  - 
    title: Invent two words
    completion:
      - engaged
  - 
    title: Train the model
  - 
    title: Control the alien
    completion:
      - internal
  - 
    title: 'Challenge'
    challenge: true
  - 
    title: What can you do now?
    completion:
      - external
