---
title: 외계인 언어
hero_image: images/banner.png
description: 스프라이트를 움직일 수있는 나만의 외국어 만들기
theme: orange
listed: true
copyedit: true
technologies: 스크래치
software: scratch
version: 4.0.0
last_tested: '2019-06-04'
steps:
  - 
    title: 소개
  - 
    title: 사전 훈련 된 모델 사용
  - 
    title: 새 프로젝트 만들기
    completion:
      - engaged
  - 
    title: 외계인 단어 만들기
  - 
    title: 새로운 머신 러닝 모델 훈련
  - 
    title: 스크래치에서 외계인 단어 사용
    completion:
      - internal
  - 
    title: '도전 과제 : 새로운 명령 추가'
    challenge: true
  - 
    title: 더 나아가기
