---
title: Langue extraterrestre
hero_image: images/banner.png
description: Créer ton propre langage extraterrestre pour déplacer un sprite
theme: orange
listed: true
copyedit: true
technologies: scratch
software: scratch
version: 4.0.0
last_tested: '2019-06-04'
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Configurer le projet
  - 
    title: Inventer deux mots
    completion:
      - engaged
  - 
    title: Entraîner le modèle
  - 
    title: Contrôler l'extraterrestre
    completion:
      - internal
  - 
    title: 'Défi'
    challenge: true
  - 
    title: Que peux-tu faire maintenant ?
    completion:
      - external
