---
title: Langage extraterrestre
hero_image: images/banner.png
description: Créer ton propre langage extraterrestre pour déplacer un sprite
theme: orange
listed: true
copyedit: true
technologies: scratch
software: scratch
version: 4.0.0
last_tested: '2019-06-04'
steps:
- title: Introduction
- title: Utiliser un modèle prédéfini
- title: Créer un nouveau projet
  completion:
  - engaged
- title: Créer des mots extraterrestres
- title: Entraîner un nouveau modèle d'apprentissage machine
- title: Utiliser des mots extraterrestres dans Scratch
  completion:
  - internal
- title: 'Défi : ajouter de nouvelles commandes'
  challenge: true
