---
title: Lingua straniera
hero_image: images/banner.png
description: Crea la tua lingua aliena per spostare uno sprite
theme: orange
listed: true
copyedit: true
technologies: scratch
software: scratch
version: 4.0.0
last_tested: '2019-06-04'
steps:
  - 
    title: Introduzione
  - 
    title: Usa un modello predisposto
  - 
    title: Crea un nuovo progetto
    completion:
      - engaged
  - 
    title: Crea parole aliene
  - 
    title: Addestra un nuovo modello di apprendimento automatico
  - 
    title: Usa parole aliene in Scratch
    completion:
      - internal
  - 
    title: 'Sfida: aggiungi nuovi comandi'
    challenge: true
  - 
    title: E adesso?
